services:
  mysql:
    image: mysql:8.0
    container_name: netlock-mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "netlock-dev"
      MYSQL_DATABASE: "netlock"
    command:
      - --skip-log-bin
      - --innodb_buffer_pool_size=512M
      - --innodb_log_file_size=256M
      - --innodb_flush_log_at_trx_commit=2
      - --max_connections=200
    volumes:
      - netlock-mysql:/var/lib/mysql
    networks:
      - netlock

  netlock-rmm-server:
    image: nicomak101/netlock-rmm-server:latest
    platform: linux/amd64
    container_name: netlock-rmm-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:7080:7080"
    environment:
      - TZ=America/Santiago
    volumes:
      - ./netlock/server/appsettings.json:/app/appsettings.json:ro
      - netlock-server-internal:/app/internal
      - netlock-server-files:/app/www/private/files
    depends_on:
      - mysql
    networks:
      - netlock

  netlock-rmm-web-console:
    image: nicomak101/netlock-rmm-web-console:latest
    platform: linux/amd64
    container_name: netlock-rmm-web-console
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - TZ=America/Santiago
    volumes:
      - ./netlock/web_console/appsettings.json:/app/appsettings.json:ro
      - netlock-web-internal:/app/internal
    depends_on:
      - mysql
      - netlock-rmm-server
    networks:
      - netlock

networks:
  netlock:
    driver: bridge

volumes:
  netlock-mysql:
  netlock-server-internal:
  netlock-server-files:
  netlock-web-internal:
